--- QUAN LY NHAN SU VER 2 ---
---   MTAZero ----
GO
	USE MASTER
GO
	DROP DATABASE QLNHANSU
GO
	CREATE DATABASE QLNHANSU
GO
	USE QLNHANSU
GO
--- DANH MUC ---
GO
	CREATE TABLE PHONGBAN(
		ID INT IDENTITY PRIMARY KEY,
		TEN NVARCHAR(MAX),
		IDCAPTREN INT,
		FOREIGN KEY (IDCAPTREN) REFERENCES PHONGBAN(ID)
	)
GO
	CREATE TABLE CHUCVU(
		ID INT IDENTITY PRIMARY KEY,
		TEN NVARCHAR(MAX),
		PHUCAPCHUCVU FLOAT
	)
GO
	CREATE TABLE NGOAINGU(
		ID INT IDENTITY PRIMARY KEY,
		TEN NVARCHAR(MAX)
	)
GO
	CREATE TABLE TRINHDOHOCVAN(
		ID INT IDENTITY PRIMARY KEY,
		TEN NVARCHAR(MAX)
	)
GO
	CREATE TABLE TONGIAO(
		ID INT IDENTITY PRIMARY KEY,
		TEN NVARCHAR(MAX)
	)
GO
	CREATE TABLE DANTOC(
		ID INT IDENTITY PRIMARY KEY,
		TEN NVARCHAR(MAX)
	)
GO
	CREATE TABLE TINH(
		ID INT IDENTITY PRIMARY KEY,
		TEN NVARCHAR(MAX)
	)
GO
	CREATE TABLE HUYEN(
		ID INT IDENTITY PRIMARY KEY,
		TEN NVARCHAR(MAX),
		TINHID INT,
			FOREIGN KEY (TINHID) REFERENCES TINH(ID)
	)
GO
	CREATE TABLE XA(
		ID INT IDENTITY PRIMARY KEY,
		TEN NVARCHAR(MAX),
		HUYENID INT,
			FOREIGN KEY (HUYENID) REFERENCES HUYEN(ID)
	)
GO
	CREATE TABLE QUANHEGD(
		ID INT IDENTITY PRIMARY KEY,
		TEN NVARCHAR(MAX)
	)
GO
	CREATE TABLE LUONG(
		ID INT IDENTITY PRIMARY KEY,
		HESOLUONG FLOAT,
		THAMNIENVUOTKHUNG FLOAT,
		HESOCHENHLECHBAOLUU FLOAT,
		TRACHNHIEM FLOAT,
		DOCHAI FLOAT,
		DACTHUNGHE FLOAT,
		DANGUYVIEN FLOAT,
		HUONGDANTHUVIEC FLOAT
	)
GO
	CREATE TABLE THAMSOHETHONG(
		ID INT IDENTITY PRIMARY KEY,
		VALUE INT -- GIÁ TRỊ, CỘT ĐẦU TIÊN TRONG BẢNG LÀ LƯƠNG CƠ BẢN
	)
GO
--- BANG DU LIEU ---
GO
	CREATE TABLE NHANVIEN(
		ID INT IDENTITY PRIMARY KEY,
		MACCVC VARCHAR(MAX),
		MANV VARCHAR(MAX),
		PHONGBANID INT,
			FOREIGN KEY (PHONGBANID) REFERENCES PHONGBAN(ID),
		CHUCVUID INT, 
			FOREIGN KEY (CHUCVUID) REFERENCES CHUCVU(ID),
		HOTEN NVARCHAR(MAX),
		NGAYSINH DATETIME,
		GIOITINH INT, 
		MASOTHUE NVARCHAR(MAX),
		SOLAODONG NVARCHAR(MAX),
		NOISINH NVARCHAR(MAX),
		DIACHI NVARCHAR(MAX),
		CMND VARCHAR(MAX),
		NGAYCAP DATETIME,
		XAID INT,
			FOREIGN KEY (XAID) REFERENCES XA(ID), --- TRONG XA DA CO THONG TIN HUYEN VA TINH
		DANTOCID INT,
			FOREIGN KEY (DANTOCID) REFERENCES DANTOC(ID),
		TONGIAOID INT,
			FOREIGN KEY (TONGIAOID) REFERENCES TONGIAO(ID),
		TRINHDOHOCVANID INT,
			FOREIGN KEY (TRINHDOHOCVANID) REFERENCES TRINHDOHOCVAN(ID),
		ANH VARBINARY(MAX),
		DANG INT, --- 0 : Chưa kết nạp, 1: Đang là đảng viên dự bị, 2: Đảng viên chính thức, 3: Đã ra khỏi Đảng
		MATKHAU VARCHAR(MAX),
		LUONGID INT,
			FOREIGN KEY (LUONGID) REFERENCES LUONG(ID),
		LOAIHOPDONG INT DEFAULT 0, -- 0: Viên chức, 1: Hợp đồng 68, 2: Hợp đồng ngắn hạn
	)
GO
	CREATE TABLE TAIKHOAN(
		ID INT IDENTITY PRIMARY KEY,
		USERNAME VARCHAR(MAX),
		PASSWORD VARCHAR(MAX),
		NHANVIENID INT,
			FOREIGN KEY (NHANVIENID) REFERENCES NHANVIEN(ID)
	)
GO	
	CREATE TABLE NGOAINGUNHANVIEN(
		ID INT IDENTITY PRIMARY KEY,
		NHANVIENID INT,
			FOREIGN KEY (NHANVIENID) REFERENCES NHANVIEN(ID),
		NGOAINGUID INT,
			FOREIGN KEY (NGOAINGUID) REFERENCES NGOAINGU(ID)
	)
GO
	CREATE TABLE CONGVIECNHV(
		ID INT IDENTITY PRIMARY KEY,
		NHANVIENID INT,
			FOREIGN KEY (NHANVIENID) REFERENCES NHANVIEN(ID),
		TEN NVARCHAR(MAX),
		NGAYGIAOVIEC DATETIME, 
		NGAYBATDAU DATETIME,
		NGAYKETTHUC DATETIME,
		NGUOIGIAOVIEC INT,
			FOREIGN KEY (NGUOIGIAOVIEC) REFERENCES NHANVIEN(ID),
		TRANGTHAI INT, -- 0: MOI NHAN VIEC, 1: DANG THUC HIEN, 2: HOANTHANH, 3: DUNG, 4 : HUY, 5- CHUYEN
		GHICHU NVARCHAR(MAX)
	)
GO
	CREATE TABLE HOPDONGLAODONG(
		ID INT IDENTITY PRIMARY KEY,
		NHANVIENID INT,
			FOREIGN KEY (NHANVIENID) REFERENCES NHANVIEN(ID),
		LUONGID INT,
			FOREIGN KEY (LUONGID) REFERENCES LUONG(ID),
		NOIDUNGCONGVIEC NVARCHAR(MAX)
	)
GO
	CREATE TABLE BAOHIEMXAHOI(
		ID INT IDENTITY PRIMARY KEY,
		NHANVIENID INT,
			FOREIGN KEY (NHANVIENID) REFERENCES NHANVIEN(ID),
		SOBAOHIEM NVARCHAR(MAX),
		NGAYLAMSO DATETIME,
		NGAYCAPSO DATETIME,
		NOICAP NVARCHAR(MAX),
		NGAYTHOIBAOHIEM DATETIME
	)	
GO
	CREATE TABLE BAOHIEMYTE(
		ID INT IDENTITY PRIMARY KEY,
		NHANVIENID INT,
			FOREIGN KEY (NHANVIENID) REFERENCES NHANVIEN(ID),
		SOTHE VARCHAR(MAX),
		BATDAU DATETIME, --- THOI GIAN BAT DAU CO HIEU LUC
		KETTHUC DATETIME,
		NGAYCAP DATETIME,
		NOICAP NVARCHAR(MAX)
	)
GO
	CREATE TABLE QUATRINHCONGTAC(
		ID INT IDENTITY PRIMARY KEY,
		NHANVIENID INT, 
			FOREIGN KEY (NHANVIENID) REFERENCES NHANVIEN(ID),
		BATDAU DATETIME,
		KETTHUC DATETIME,
		CONGTY NVARCHAR(MAX),
		DIACHI NVARCHAR(MAX),
		DIENTHOAI NVARCHAR(MAX),
		NOIDUNGCONGTAC NVARCHAR(MAX)
	)
GO
	CREATE TABLE KHENTHUONG(
		ID INT IDENTITY PRIMARY KEY,
		NHANVIENID INT,
			FOREIGN KEY (NHANVIENID) REFERENCES NHANVIEN(ID),
		NOIDUNG NVARCHAR(MAX),
		NGAY DATETIME
	)
GO
	CREATE TABLE KYLUAT(
		ID INT IDENTITY PRIMARY KEY,
		NHANVIENID INT,
			FOREIGN KEY (NHANVIENID) REFERENCES NHANVIEN(ID),
		NOIDUNG NVARCHAR(MAX),
		NGAY DATETIME
	)
GO
	CREATE TABLE BANGCAP(
		ID INT IDENTITY PRIMARY KEY,
		NHANVIENID INT,
			FOREIGN KEY (NHANVIENID) REFERENCES NHANVIEN(ID),
		NGAY DATETIME,
		CHUYENNGANH NVARCHAR(MAX), --- chuyên ngành của tấm bằng
		MABANG VARCHAR(MAX), --- mã số trên bằng
		LOAITOTNGHIEP NVARCHAR(MAX), --- Xuất sắc, Giỏi, Khá
		LOAIBANG NVARCHAR(MAX) --- Đại học, cao đẳng
	)	
GO
	CREATE TABLE QUATRINHHOCTAP(
		ID INT IDENTITY PRIMARY KEY,
		NHANVIENID INT,
			FOREIGN KEY (NHANVIENID) REFERENCES NHANVIEN(ID),
		BATDAU DATETIME,
		KETTHUC DATETIME,
		NOIDUNG NVARCHAR(MAX)
	)
GO
	CREATE TABLE THANNHAN(
		ID INT IDENTITY PRIMARY KEY,
		HOTEN NVARCHAR(MAX),
		NGAYSINH DATETIME,
		GIOITINH INT,
		QUEQUAN NVARCHAR(MAX),
		CMND VARCHAR(MAX),
		QUANHEGDID INT,
			FOREIGN KEY (QUANHEGDID) REFERENCES QUANHEGD(ID),
		NHANVIENID INT,
			FOREIGN KEY (NHANVIENID) REFERENCES NHANVIEN(ID)
	)
GO
	CREATE TABLE TAISAN(
		ID INT IDENTITY PRIMARY KEY,
		NHANVIENID INT,
			FOREIGN KEY (NHANVIENID) REFERENCES NHANVIEN(ID),
		TENTAISAN NVARCHAR(MAX),
		GIATRI INT,
		SOLUONG INT,
		BATDAUSOHUU DATETIME,
		GHICHU NVARCHAR(MAX)
	)
GO
	CREATE TABLE CHAMCONG(
		ID INT IDENTITY PRIMARY KEY,
		NHANVIENID INT,
			FOREIGN KEY (NHANVIENID) REFERENCES NHANVIEN(ID),
		NGAY DATETIME,
		LOAI INT, --- 0 : NGÀY BÌNH THƯỜNG, 1: NGÀY TRỰC
	)
GO
-- THEM DU LIEU MAU --
	INSERT INTO CHUCVU(TEN, PHUCAPCHUCVU) VALUES(N'Giám đốc', 6.0)
	INSERT INTO PHONGBAN(TEN) VALUES(N'Phòng Giám Đốc')
	INSERT INTO NHANVIEN(HOTEN, CHUCVUID,PHONGBANID, MANV, MATKHAU, GIOITINH, NGAYSINH) VALUES (N'Bùi Việt Bắc', 1, 1, 'NV01', '123456',1, '3-8-1996')
GO
